### ISSUE TITLE
no such table: main.chats_meta

### ISSUE THREAD

**Issue by NohamR** [gavindsouza/instagram-to-sqlite#1]
Hey ! I exported my data to json and I wanted to see the data they have about me. I cloned your repo and installed the files. But when i try to run "instagram-to-sqlite chats insta-chats.db ~/Downloads/no.0ham_20230604.zip", I'm getting the error : "no such table: main.chats_meta"

![image](https://github.com/gavindsouza/instagram-to-sqlite/assets/100566912/f157a38b-d4d0-4bbf-9559-447b8bb44028)
Can you help me ?
Thank you in advance !

**Comment by gavindsouza** [comment]
Hey, I can't seem to replicate this (although this is 2 months after your post). If you can provide more information, I'd be happy to help any way I can.
